### ISSUE TITLE
[Regression] Can't compare structs

### ISSUE THREAD

**Issue by Suchiman** [bridgedotnet/Bridge#1817]
### Expected

I can compare structs

### Actual

I cannot compare structs anymore in Bridge 15.0

```
Operator '!=' cannot be applied to operands of type 'KeyValuePair<string, string>' and 'KeyValuePair<string, string>
```

### Steps To Reproduce

http://deck.net/641212bef3e4715e6012497313b35485

```csharp
public class App
{
    public static void Main()
    {
            List<KeyValuePair<string, string>> parameter = new List<KeyValuePair<string, string>>();
            var result = parameter.FirstOrDefault(x => x.Key == key);

            if (result != default(KeyValuePair<string, string>))
            {
                        // ...
            }
    }
}
```

**PRO TIP:** Create a [Deck.NET](http://deck.net) sample for easy testing and sharing.

**Comment by vladsch** [comment]
It is correct behaviour. KeyValuePair was changed to struct from class (like in .NET)
Your test sample in .NET application gives the same compilation error

**Comment by vladsch** [comment]
Use `result.Equals` method

**Comment by geoffreymcgill** [comment]
Here's your original sample in DotNetFiddle and Deck. 

https://dotnetfiddle.net/TmFO2R

http://deck.net/641212bef3e4715e6012497313b35485

Both returning the same Exception.

**Comment by Suchiman** [comment]
Sorry guys, i feel a little bit stupid about this, i swear i tried copying it into another project and roslyn didn't light up an error in intellisense 😅 but when trying to compile the sample in a fresh console application it does indeed fail.

**Comment by geoffreymcgill** [comment]
No worries. This should not have worked in previous Bridge releases (pre 15.0), so it looks like a valid regression.
