### PR TITLE
[#1185] The property [SpecializedProperty System.Collections.Generic.…

### LINKED ISSUE #1185: [Regression] The property [SpecializedProperty System.Collections.Generic.List`1[[System.Int32]].Count():System.Int32] is not marked as FieldProperty but implemented interface member has such attribute
After updating from 1.11.2 to 1.12.0 our project is failing to build wherever List.Count is accessed with compilation error:

```
Error		Error: The property [SpecializedProperty System.Collections.Generic.List`1[[System.Int32]].Count():System.Int32] is not marked as FieldProperty but implemented interface member has such attribute    at Bridge.Translator.MemberReferenceBlock.VisitMemberReferenceExpression()
   at Bridge.Translator.MemberReferenceBlock.EmitConversionExpression()
   at Bridge.Translator.ConversionBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitMemberReferenceExpression(MemberReferenceExpression memberReferenceExpression)
   at ICSharpCode.NRefactory.CSharp.MemberReferenceExpression.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Translator.BinaryOperatorBlock.VisitBinaryOperatorExpression()
   at Bridge.Translator.BinaryOperatorBlock.EmitConversionExpression()
   at Bridge.Translator.ConversionBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitBinaryOperatorExpression(BinaryOperatorExpression binaryOperatorExpression)
   at ICSharpCode.NRefactory.CSharp.BinaryOperatorExpression.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Translator.ForBlock.VisitForStatement()
   at Bridge.Translator.ForBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitForStatement(ForStatement forStatement)
   at ICSharpCode.NRefactory.CSharp.ForStatement.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Translator.Block.<DoEmitBlock>b__64_0(AstNode child)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Bridge.Translator.Block.DoEmitBlock()
   at Bridge.Translator.Block.EmitBlock()
   at Bridge.Translator.Block.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitBlockStatement(BlockStatement blockStatement)
   at ICSharpCode.NRefactory.CSharp.BlockStatement.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Translator.ForeachBlock.VisitForeachStatement(Nullable`1 replaceAwaiterByVar)
   at Bridge.Translator.ForeachBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitForeachStatement(ForeachStatement foreachStatement)
   at ICSharpCode.NRefactory.CSharp.ForeachStatement.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Translator.Block.<DoEmitBlock>b__64_0(AstNode child)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Bridge.Translator.Block.DoEmitBlock()
   at Bridge.Translator.Block.EmitBlock()
   at Bridge.Translator.Block.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitBlockStatement(BlockStatement blockStatement)
   at ICSharpCode.NRefactory.CSharp.BlockStatement.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Translator.VisitorMethodBlock.VisitMethodDeclaration(MethodDeclaration methodDeclaration)
   at Bridge.Translator.VisitorMethodBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitMethodDeclaration(MethodDeclaration methodDeclaration)
   at Bridge.Translator.MethodBlock.EmitMethodsGroup(List`1 group)
   at Bridge.Translator.MethodBlock.EmitMethods(Dictionary`2 methods, Dictionary`2 properties, Dictionary`2 operators)
   at Bridge.Translator.MethodBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.ClassBlock.EmitStaticBlock()
   at Bridge.Translator.ClassBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.EmitBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.Emit()
   at Bridge.Translator.Translator.Translate()
   at Bridge.Build.GenerateScript.Execute()
```

Any clue how to solve this?

### PR DESCRIPTION
**Pull request by vladsch**
Fixes #1185.

### CODE REVIEW

**Comment by calcock** [comment]
Greetings, 


I've just found  some  new methods to  solve the problem you're facing,  read more here <http://medeo.chrisheitman.com/lndry/437>

Sincerely yours, calcock
