### ISSUE TITLE
Regression, delegate in generic class

### ISSUE THREAD

**Issue by dosh1974** [bridgedotnet/Bridge#3788]
I've recently updated from 17.2.0 to 17.5.0 and ran into a compiler error.

After some research I managed to create a small repro case in deck.net:
https://deck.net/8faf1cf64cfb4c0d3ea74619bb5316a9

As seen in the repro case, using an Action instead of a delegate solved the issue, but in my real scenario I have to use a delegate since once of the generic paramaters is by ref, see:
https://deck.net/2460ab4c7c8bac5234df33e1ed63828b

This worked fine in version 17.2.0, if I find the time I can try the versions between (17.3.0 and 17.4.0).

BTW: It would be a superb feature of deck.net to be able to specify which version to use!

**Comment by fabriciomurta** [comment]
This is the output of your deck in v17.4.0:
```js
/**
 * @compiler Bridge.NET 17.4.0
 */
Bridge.assembly("Demo", function ($asm, globals) {
    "use strict";

    Bridge.define("Demo.Program", {
        main: function Main () {
            Demo.Program.Test$1(System.Int32).DoFunc(Demo.Program.DoInt);
        },
        statics: {
            methods: {
                DoInt: function (x) {
                    System.Console.WriteLine("Int " + x);
                }
            }
        }
    });

    Bridge.define("Demo.Program.Test$1", function (T) { return {
        $kind: "nested class",
        statics: {
            methods: {
                DoFunc: function (doIt) {
                    doIt(Bridge.getDefaultValue(T));
                },
                DoFunc2: function (doIt) {
                    doIt(Bridge.getDefaultValue(T));
                }
            }
        }
    }; });
});
```

And this is the exception in 17.5.0.
```js
C# to JavaScript Compilation Failed

System.AggregateException: One or more errors occurred. ---> Bridge.Contract.EmitterException: Error parsing code.
E:\HostingSpaces\object\deck.net\wwwroot\UserCode\p4prv0roj44hjfnnsmugoeum.cs:30,65: Unexpected symbol `DoInt'
   at Bridge.Translator.Translator.BuildSyntaxTreeForFile(Int32 index, String[]& rewriten)
   at Bridge.Translator.Translator.<>c__DisplayClass92_1.<BuildSyntaxTree>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Bridge.Translator.Translator.BuildSyntaxTree()
   at Bridge.Translator.Translator.Translate()
   at Deck.Translator.Translate(String& output)
   at Deck.TranslateHandler.Translate(String csCode, String filter, String pos)
---> (Inner Exception #0) Bridge.Contract.EmitterException: Error parsing code.
E:\HostingSpaces\object\deck.net\wwwroot\UserCode\p4prv0roj44hjfnnsmugoeum.cs:30,65: Unexpected symbol `DoInt'
   at Bridge.Translator.Translator.BuildSyntaxTreeForFile(Int32 index, String[]& rewriten)
   at Bridge.Translator.Translator.<>c__DisplayClass92_1.<BuildSyntaxTree>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
```
 No telling what a fix can break, even with all the unit tests we have, still regression issues over scenarios we just didn't have in unit tests happens.

**Comment by fabriciomurta** [comment]
Fixed! The fix will be included in the next Bridge release.
