### ISSUE TITLE
Does array implement IEnumerable?

### ISSUE THREAD

**Issue by txdv** [bridgedotnet/Bridge#369]
Hey guys, for some reason it seems that Array doesn't implement IEnumerable, this is my code for vanilla csharp:

```csharp
	public static class ExtensionClass
	{
		static Dictionary<string, string> symbols = new Dictionary<string, string>() {
			{ "b", "Hello World" },
			{ "c", "Hello John" },
		};

		public static IEnumerable<T> UniqueElements<T>(this IEnumerable<IEnumerable<T>> elements)
		{
			return elements.SelectMany(i => i).Distinct().OrderBy(i => i);
		}

		public static void Main(string[] args)
		{
			foreach (var a in symbols.Select(i => i.Value.Split(' ')).UniqueElements<string>()) {
				Console.WriteLine(a);
			}
		}
	}
```

The same thing doesn't work for Bridge.net, I have to modify it like this to get it working:

```csharp
	public static class ExtensionClass
	{
		static Dictionary<string, string> symbols = new Dictionary<string, string>() {
			{ "b", "Hello World" },
			{ "c", "Hello John" },
		};

		public static IEnumerable<T> UniqueElements<T>(this IEnumerable<T[]> elements)
		{
			return elements.SelectMany(i => i).Distinct().OrderBy(i => i);
		}

		public static void Main(string[] args)
		{
			foreach (var a in symbols.Select(i => i.Value.Split(" ")).UniqueElements<string>()) {
				Console.WriteLine(a);
			}
		}
```

It works with vanilla C# (except that in vanilla csharp).

Notice that I changed the argument in the UniqueElements method from IEnumerable<IEnumerable<T>> to IEnumerable<T[]> and that Split now takes a string, and no char.

I don't know what to make of this, can you guys elaborate?

**Comment by vladsch** [comment]
For me both of your versions works correctly, compiles without any problems and output is
Hello
John
World

**Comment by txdv** [comment]
I might be using not the latest release, I'll take a look into that.

**Comment by vladsch** [comment]
Don't worry. Don't hesitate to post any strange issues
By the way, see your code in live, it works fine
http://live.bridge.net/#1c4c2c56751e76ede4c4

**Comment by txdv** [comment]
Ok, I took a look, there is no Split(char c) overload anywhere in Bridge https://github.com/bridgedotnet/Bridge/blob/master/Bridge/System/String.cs#L653

But the live editor seems to somehow compile it, but I just used whatever different name, and it stilled worked: http://live.bridge.net/#d4a9e9060339b3ca39fd

It seems like the live editor is using some kind of dynamic conversion, as if all objects were dynamic or something.

I also checked the reference source, and there a lot of definitions of Split methods which are not present in Bridges String.cs: http://referencesource.microsoft.com/#mscorlib/system/string.cs,931

**Comment by txdv** [comment]
O god, upgrading to 1.8 was a complete disaster, it doesn't generate the js files anymore :(

**Comment by txdv** [comment]
And when I try to build Bridge and all it dependencies, I now get a lot of errors, did someone turn on error on warning?

**Comment by vladsch** [comment]
I will add Split overloads to Bridge
>Are you going to use Saltarelles CoreLib in Bridge.net 2.0 or are you going to work on the corelib in the Bridge repository?

**Comment by txdv** [comment]
I can do it too... if 1.8 would work with monodevelop :/

**Comment by vladsch** [comment]
>Application.cs(33,33): Error CS1593: Delegate `System.Action' does not take `1' arguments (CS1593) (Web)
Can you post a code which raise such error?

**Comment by vladsch** [comment]
>Also creating a new project and trying to add Bridge.net turns into a recursive invocation of xbuild when building that project.

**Comment by txdv** [comment]
> v2 will use Saltarelles CoreLib

Well, why are you working then on Bridges corelib now and reporting so many errors and such?

**Comment by vladsch** [comment]
We don't work on Bridge corelib actively, only bug fixes and requests from members which currently use v1

**Comment by txdv** [comment]
@vladsch Don't waste your time with Split then, I can wait for v2.

**Comment by vladsch** [comment]
> reporting so many errors
what errors do you mean? If Bridge has no some some methods which are presented in .NET then i would not consider it as error. You can always to report about such method and we will happy to add it

About mono, we will try to investigate mono issue as soon as possible, sorry for inconvinience

**Comment by txdv** [comment]
if it is just for me, then don't do it, as I said, I can wait for v2.

**Comment by txdv** [comment]
> what errors do you mean? If Bridge has no some some methods which are presented in .NET then i would not consider it as error. You can always to report about such method and we will happy to add it

When I try to compile the source code, it reports a lot of warnings as errors (unused variables and stuff)

**Comment by DaniilVeriga** [comment]
@txdv, could you, please, clarify how you updated to 1.8.0? Do you download VSCode zip package or somehow else? 

Also agree with @vladsch that a test case to reproduce this issue is greatly appreciated:
> Application.cs(33,33): Error CS1593: Delegate System.Action' does not take1' arguments (CS1593) (Web)

**Comment by txdv** [comment]
@DaniilVeriga I used monodevelop and its built in nuget package manager. For some reason I was able to get it running by just installing Bridge 1.7.0 the first time in an empty project, then when I upgraded to 1.8.0 it stopped the js files. When I try to create an empty project and add the Bridge 1.8.0 nuget package, then to compile, it just spawns a bunch of xbuild processes recursively.

As for the error, the error occurs because I am trying to pass a char to the Split function and there is only a string definition.

I don't think you need to invest time in both, just work on releasing v2 faster ;)

**Comment by fabriciomurta** [comment]
Hello @txdv, now that we know that a recent change broke the build process on Linux and also our latest release do not build on said platform we can naught but investigate it. Before 1.8 release I've built a couple test programs on OS X with no problems, but some commits before its release might still have taken place and resulted in that xbuild loop issue.

The issue with the warnings as errors is due to #370, we will not close that issue until it builds on both Linux and Windows versions. To have your local copy working right now, you can revert the related commits or just checkout @7c886519. Or, also, unset the TreatWarningsAsErrors option in the project files.

**Comment by fabriciomurta** [comment]
I've just created a new project using Bridge.NET 1.8 and XamarinStudio. Worked fine, of course, after overcoming an issue on Mono itself, that is a known issue and has an open entry on MonoDevelop website.

Can you check on your project if you have the '**do not reference mscorlib.dll' checked**? Unfortunately, xbuild ignores it if it is set on an included file, and we have to set this manually in the project options. Luckily we can do this from project properties on XamarinStudio/MonoDevelop, I doubt that would be an option on Visual Studio. :)

<img width="750" alt="Do not include mscorlib.dll checkbox" src="https://cloud.githubusercontent.com/assets/10730372/9366377/65828a64-468d-11e5-9a85-d32b56d5d2ba.png">

The checkbox is unchecked by default and, until Mono fixes its bug with detecting <NostdLib /> project option on included files, I don't see better solution than just checking that box on new projects.

In my case, I just created an 'Empty Project', added the NuGet package, created an empty class (fixing the `using` lines) then checked the box to suppress references to mscorlib.dll.
<img width="628" alt="Create new empty library project" src="https://cloud.githubusercontent.com/assets/10730372/9366509/360508b0-468e-11e5-859c-e8b0eafc923b.png">
<img width="819" alt="NuGet package selection" src="https://cloud.githubusercontent.com/assets/10730372/9366513/3a0b09be-468e-11e5-9afa-39894993e0cb.png">

Unfortunately, so far I wasn't able to reproduce the xbuild recursive calling error.

**Comment by fabriciomurta** [comment]
Back to the first post on this issue, the code
```csharp
public static class ExtensionClass
    {
        static Dictionary<string, string> symbols = new Dictionary<string, string>() {
            { "b", "Hello World" },
            { "c", "Hello John" },
        };

        public static IEnumerable<T> UniqueElements<T>(this IEnumerable<IEnumerable<T>> elements)
        {
            return elements.SelectMany(i => i).Distinct().OrderBy(i => i);
        }

        public static void Main(string[] args)
        {
            foreach (var a in symbols.Select(i => i.Value.Split(' ')).UniqueElements<string>()) {
                Console.WriteLine(a);
            }
        }
    }
```
Can't be built on both windows or linux. Message is related to `i.Value.Split()` not having overload to `char`.
```
The best overloaded method match for 'string.Split(string)' has some invalid arguments
Argument 1: cannot convert from 'char' to 'string'
```

**Comment by fabriciomurta** [comment]
Commit above is NOT merged on upstream (yet). Waiting feedback from team. If you want to test it, change bridge into branch issue369.
The commit does not fix building on Linux. That fix will follow soon directly on master branch.

**Comment by LeonidVeriga** [comment]
We have `public extern string[] Split(char separator);` implemented in the current `1.10.2`.
